version: '3.8'

services:
  php:
    build: .
    container_name: babyslim
    ports:
      - "15091:80"
    volumes:
      - ./web:/var/www/html
    read_only: true
    networks:
      - webnet

networks:
  webnet: