version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:8-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:9003 -t public
        environment:
            docker: "true"
        ports:
            - "9003:9003"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
