version: '3.8'

services:
  php:
    build: .
    container_name: sanitizer
    ports:
      - "2000:80"
    volumes:
      - .:/var/www/html:ro
    read_only: true
    networks:
      - webnet

networks:
  webnet:
