version: '3'
services:
  hacktod:
    container_name: Curve_Enjoyer
    restart: always
    build:
      context: .
      args:
        binary: server.py
    ports:
      - "8011:5000" # exposed:local
    read_only: true
