version: '3'
services:
  hacktod:
    container_name: Super-Guesser
    restart: always
    build:
      context: .
      args:
        binary: server.py
    ports:
      - "8010:5000"
    read_only: true